# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EaEIQJf8Yad57EujmxIwFJf3ToeWHXxN
"""

#EXPLORATORY DATA ANALYSIS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#importing the data set
zahid=pd.read_csv('https://raw.githubusercontent.com/zahid514326/EDA-data-set/main/Breast_cancer_data.csv')
zahid

zahid.shape

x=zahid.head()
x

#Checking for duplicate data and null records
zahid.isnull().sum

"""It means there are no null entries in our data"""

#Removing duplicate entries
zahid.drop_duplicates(inplace = True)
zahid

"""It means there are no duplicate entries in our data set"""

#Finding correlaion
plt.figure(figsize = (12,6))
sns.heatmap(zahid.corr(),annot=True,cmap = 'BrBG')
plt.show()

sns.pairplot(zahid)
plt.show()

"""After visualizing this, We can clearly say that:
1. mean_perimeter and mean_radius is complete correlated(100%)
2. mean_area and mean_radius(99%)
3. mean_area and mean_perimeter(99%)

So, if we drop mean_perimeter column because it is highly correlateed with mean radius and as well as we will drop mean area.
"""

#Removing outliers
zahid1=zahid.drop(columns = ['mean_perimeter','mean_area'], axis = 1)
zahid1

"""You can clearly see that in above data two columns are dropped."""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# zahid.hist(bins=30,figsize=(18,12))
# plt.show()
#